name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # - name: Cache Cargo registry
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cargo/registry
    #     key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-cargo-registry-
    #
    # - name: Cache Cargo index
    #   uses: actions/cache@v3
    #   with:
    #     path: ~/.cargo/git
    #     key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-cargo-index-
    #
    # - name: Cache Cargo build
    #   uses: actions/cache@v3
    #   with:
    #     path: target
    #     key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-cargo-build-

    - name: Use rust nightly
      run: rustup default nightly

    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl

    - uses: Swatinem/rust-cache@v2

    - name: Build
      run: cargo build

    - name: Install cargo nextest
      run: cargo install cargo-nextest

    - name: Run tests
      run: cargo nextest run --all-targets --all-features -j num-cpus

    - name: install cargo clippy
      run: rustup component add clippy

    - name: Lint
      run: cargo clippy --all-targets --all-features -- -D warnings
